version: "3.5"

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - app-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: musics
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret

volumes:
  app-data:
